In [2]:
import numpy as np

row_v = np.array([10,15,20])
col_v = np.array([[10],[20],[30]])
print(row_v)
print(col_v)

[10 15 20]
[[10]
 [20]
 [30]]


In [6]:
matrix = np.array([[10,20,40],[5,6,7]])
print(matrix)

[[10 20 40]
 [ 5  6  7]]


In [9]:
print(np.array([matrix[:,-1]]))

[[40  7]]


In [10]:
matrix.shape

(2, 3)

In [11]:
matrix.size

6

In [13]:
matrix.ndim

2

In [16]:
np.max(matrix,axis = 0)

array([10, 20, 40])

In [17]:
np.mean(matrix)

14.666666666666666

In [19]:
print(matrix)
print(matrix.reshape(3,2))

[[10 20 40]
 [ 5  6  7]]
[[10 20]
 [40  5]
 [ 6  7]]


In [21]:
print(matrix.reshape(6))

[10 20 40  5  6  7]


In [25]:
print(matrix.reshape(6,-1))

[[10]
 [20]
 [40]
 [ 5]
 [ 6]
 [ 7]]


In [26]:
print(matrix.T)

[[10  5]
 [20  6]
 [40  7]]


In [28]:
print(matrix.diagonal())

[10  6]


In [180]:
np.random.randint([[5,6],[10,10]])

array([[4, 4],
       [2, 2]])

In [194]:
np.random.normal(1.0,2.0,4)

array([ 3.23207609,  3.37648275,  1.96419345, -0.47109198])

In [211]:
#Pandas

import pandas as pd

#DataFrame

dict_1 = {"car": ["city","Verna", "Punto"],"brand":["tesla","honda",'bmw'],"cost": [90000,20000,50000]}
print(dict_1)

auto = pd.DataFrame(dict_1)
auto

{'car': ['city', 'Verna', 'Punto'], 'brand': ['tesla', 'honda', 'bmw'], 'cost': [90000, 20000, 50000]}


car  brand   cost
0   city  tesla  90000
1  Verna  honda  20000
2  Punto    bmw  50000

In [294]:
data = pd.read_csv("Titanic.csv")

In [216]:
data.head(6)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   
5                             Anderson, Mr Harry    1st  47.00    male   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         1  
5         1

In [218]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1313 entries, 0 to 1312
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      1313 non-null   object 
 1   PClass    1312 non-null   object 
 2   Age       756 non-null    float64
 3   Sex       1313 non-null   object 
 4   Survived  1313 non-null   int64  
dtypes: float64(1), int64(1), object(3)
memory usage: 51.4+ KB


In [221]:
data.shape

(1313, 5)

In [222]:
data.columns

Index(['Name', 'PClass', 'Age', 'Sex', 'Survived'], dtype='object')

In [231]:
data["Name"].value_counts()

Connolly, Miss Kate             2
Carlsson, Mr Frans Olof         2
Kelly, Mr James                 2
Allen, Miss Elisabeth Walton    1
Jensen, Mr Hans Peder           1
                               ..
Herman, Mr Samuel               1
Herman, Miss Kate               1
Herman, Miss Alice              1
Hart, Miss Eva Miriam           1
Zimmerman, Leo                  1
Name: Name, Length: 1310, dtype: int64

In [237]:
data["Sex"].unique()

array(['female', 'male'], dtype=object)

In [248]:
data[['Name','Sex']]

Name     Sex
0                      Allen, Miss Elisabeth Walton  female
1                       Allison, Miss Helen Loraine  female
2               Allison, Mr Hudson Joshua Creighton    male
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)  female
4                     Allison, Master Hudson Trevor    male
...                                             ...     ...
1308                             Zakarian, Mr Artun    male
1309                         Zakarian, Mr Maprieder    male
1310                               Zenni, Mr Philip    male
1311                               Lievens, Mr Rene    male
1312                                 Zimmerman, Leo    male

[1313 rows x 2 columns]

In [259]:
data.iloc[0:5,3].values

array(['female', 'female', 'male', 'female', 'male'], dtype=object)

In [265]:
data.loc[:,["Name"]]

Name
0                      Allen, Miss Elisabeth Walton
1                       Allison, Miss Helen Loraine
2               Allison, Mr Hudson Joshua Creighton
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)
4                     Allison, Master Hudson Trevor
...                                             ...
1308                             Zakarian, Mr Artun
1309                         Zakarian, Mr Maprieder
1310                               Zenni, Mr Philip
1311                               Lievens, Mr Rene
1312                                 Zimmerman, Leo

[1313 rows x 1 columns]

In [284]:
data[data["Name"] == ['%Allen%']

Name PClass    Age     Sex  Survived
0     %Allen%    1st  29.00  female         1
1     %Allen%    1st   2.00  female         0
2     %Allen%    1st  30.00    male         0
3     %Allen%    1st  25.00  female         0
4     %Allen%    1st   0.92    male         1
...       ...    ...    ...     ...       ...
1308  %Allen%    3rd  27.00    male         0
1309  %Allen%    3rd  26.00    male         0
1310  %Allen%    3rd  22.00    male         0
1311  %Allen%    3rd  24.00    male         0
1312  %Allen%    3rd  29.00    male         0

[1313 rows x 5 columns]

In [288]:
auto.sort_values('cost')

car  brand   cost
1  Verna  honda  20000
2  Punto    bmw  50000
0   city  tesla  90000

In [313]:
groups = data.groupby(['Sex'])

In [314]:
groups.count()

Name  PClass  Age  Survived
Sex                                
female   462     462  288       462
male     851     850  468       851

In [303]:
grp2 = auto.groupby(['car'])
grp2.mean()

cost
car           
Punto  50000.0
Verna  20000.0
city   90000.0